name: gerrychain-environment
channels:
  - conda-forge
  - gerrychain
dependencies:
  - Fiona
  - geopandas
  - geopy
  - networkx
  - numpy
  - pandas  
  - scipy
  - seaborn
  - Shapely
  - tqdm
  - libpysal
  - pandarallel
  - haversine
