name: gerrychain-environment
channels:
  - conda-forge
dependencies:
  - gerrychain
  - fiona
  - pyproj
  - geopandas
  - geopy
  - networkx
  - numpy
  - pandas  
  - scipy
  - seaborn
  - shapely
  - tqdm
  - libpysal
  - pandarallel
  - haversine
